services: 
  xrayr: 
    image: ghcr.io/xrayr-project/xrayr:latest
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
    restart: always
    network_mode: host
    # privileged: true # wireguard需要开启
